# Generated by Django 5.2.1 on 2026-06-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LockerZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分区名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='分区编码')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '柜机分区',
                'verbose_name_plural': '柜机分区',
                'ordering': ['code'],
            },
        ),
        migrations.AlterModelOptions(
            name='lockercell',
            options={'ordering': ['zone__code', 'code'], 'verbose_name': '柜格', 'verbose_name_plural': '柜格'},
        ),
        migrations.AddField(
            model_name='lockercell',
            name='zone_name',
            field=models.CharField(default='A区', max_length=30, verbose_name='分区名称(旧)'),
        ),
        migrations.AlterField(
            model_name='lockercell',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cells', to='lockers.lockerzone', verbose_name='所属分区'),
        ),
    ]
