# Generated by Django 5.2.1 on 2026-06-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockers', '0002_lockerzone_alter_lockercell_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lockercell',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='柜格编码'),
        ),
        migrations.AlterField(
            model_name='lockercell',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后开启时间'),
        ),
        migrations.AlterField(
            model_name='lockercell',
            name='size',
            field=models.CharField(choices=[('small', '小'), ('medium', '中'), ('large', '大')], default='medium', max_length=20, verbose_name='尺寸'),
        ),
        migrations.AlterField(
            model_name='lockercell',
            name='status',
            field=models.CharField(choices=[('empty', '空闲'), ('occupied', '已占用'), ('open', '已开门'), ('maintenance', '维护中')], default='empty', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='lockercell',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=24, max_digits=5, verbose_name='温度'),
        ),
        migrations.AlterField(
            model_name='lockercell',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
